<a href="https://colab.research.google.com/github/namansehwal/Assets/blob/main/PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
sample_list = [[1,32,43,434,34,],[1,32,43,434,34,]]
sample_list

[[1, 32, 43, 434, 34], [1, 32, 43, 434, 34]]

In [3]:
np_array = np.random.rand(4,3)

In [4]:
np_array

array([[0.27149212, 0.32069481, 0.64549561],
       [0.47803345, 0.80681252, 0.28727605],
       [0.40206173, 0.40076707, 0.77868855],
       [0.93641384, 0.7548304 , 0.45530405]])

In [5]:
np_array.dtype

dtype('float64')

In [6]:
tensor_2d = torch.randn(4,3)
tensor_2d

tensor([[-1.6510, -1.6355, -0.3321],
        [-1.5823, -0.9608,  0.6821],
        [ 1.6653, -1.9637,  0.1979],
        [ 0.0513, -0.8663, -0.1687]])

In [7]:
tensor_2d.dtype

torch.float32

In [8]:
converted = torch.tensor(np_array)
converted

tensor([[0.2715, 0.3207, 0.6455],
        [0.4780, 0.8068, 0.2873],
        [0.4021, 0.4008, 0.7787],
        [0.9364, 0.7548, 0.4553]], dtype=torch.float64)

In [9]:
tensor = torch.arange(2,96,3)
tensor

tensor([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50, 53,
        56, 59, 62, 65, 68, 71, 74, 77, 80, 83, 86, 89, 92, 95])

In [10]:
tr1 = tensor.reshape(8,-1)
tr1

tensor([[ 2,  5,  8, 11],
        [14, 17, 20, 23],
        [26, 29, 32, 35],
        [38, 41, 44, 47],
        [50, 53, 56, 59],
        [62, 65, 68, 71],
        [74, 77, 80, 83],
        [86, 89, 92, 95]])

In [11]:
tr1[-1][-1] = 69
tr1

tensor([[ 2,  5,  8, 11],
        [14, 17, 20, 23],
        [26, 29, 32, 35],
        [38, 41, 44, 47],
        [50, 53, 56, 59],
        [62, 65, 68, 71],
        [74, 77, 80, 83],
        [86, 89, 92, 69]])

In [12]:
tensor

tensor([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50, 53,
        56, 59, 62, 65, 68, 71, 74, 77, 80, 83, 86, 89, 92, 69])

In [13]:
ta = torch.tensor([1,2,3,4])
tb = torch.arange(4)
tb

tensor([0, 1, 2, 3])

In [14]:
ta + tb #addition

tensor([1, 3, 5, 7])

In [15]:
torch.add(ta,tb) # tensor longhand

tensor([1, 3, 5, 7])

In [16]:
torch.subtract(ta,tb) # alias => torch.sub(ta,tb) ,ta-tb

tensor([1, 1, 1, 1])

In [17]:
torch.mul(ta,tb) # alias => torch.multiply(ta,tb) ,ta*tb

tensor([ 0,  2,  6, 12])

In [18]:
torch.div(tb,ta) # alias => tb/ta

tensor([0.0000, 0.5000, 0.6667, 0.7500])

In [19]:
#remainder Modulus
tb % ta # alias => torch.remainder(tb,ta)

tensor([0, 1, 2, 3])

In [20]:
# Exponents
ta ** tb # torch.pow(ta,tb)

tensor([ 1,  2,  9, 64])

In [21]:
# another way to write longhand
ta.pow(tb)

tensor([ 1,  2,  9, 64])

In [22]:
# reassignment
ta += tb
ta

tensor([1, 3, 5, 7])

In [23]:
tb

tensor([0, 1, 2, 3])

In [24]:
tb.add_(ta)

tensor([ 1,  4,  7, 10])

In [25]:
tb

tensor([ 1,  4,  7, 10])

In [30]:
torch.cuda.is_available()

False