<a href="https://colab.research.google.com/github/namansehwal/Assets/blob/main/PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [260]:
import torch
import numpy as np

In [261]:
sample_list = [[1,32,43,434,34,],[1,32,43,434,34,]]
sample_list

[[1, 32, 43, 434, 34], [1, 32, 43, 434, 34]]

In [262]:
np_array = np.random.rand(4,3)

In [263]:
np_array

array([[0.01591415, 0.52502809, 0.14651455],
       [0.97855851, 0.07331356, 0.54516635],
       [0.66885546, 0.7080477 , 0.79406202],
       [0.87349976, 0.28099927, 0.05670006]])

In [264]:
np_array.dtype

dtype('float64')

In [265]:
tensor_2d = torch.randn(4,3)
tensor_2d

tensor([[ 0.3708,  1.3001, -0.6518],
        [-2.6170,  1.3799,  1.0075],
        [ 0.3830,  0.6572, -0.6710],
        [-0.3175,  0.5220,  0.2700]])

In [266]:
tensor_2d.dtype

torch.float32

In [267]:
converted = torch.tensor(np_array)
converted

tensor([[0.0159, 0.5250, 0.1465],
        [0.9786, 0.0733, 0.5452],
        [0.6689, 0.7080, 0.7941],
        [0.8735, 0.2810, 0.0567]], dtype=torch.float64)

In [268]:
tensor = torch.arange(2,96,3)
tensor

tensor([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50, 53,
        56, 59, 62, 65, 68, 71, 74, 77, 80, 83, 86, 89, 92, 95])

In [269]:
tr1 = tensor.reshape(8,-1)
tr1

tensor([[ 2,  5,  8, 11],
        [14, 17, 20, 23],
        [26, 29, 32, 35],
        [38, 41, 44, 47],
        [50, 53, 56, 59],
        [62, 65, 68, 71],
        [74, 77, 80, 83],
        [86, 89, 92, 95]])

In [270]:
tr1[-1][-1] = 69
tr1

tensor([[ 2,  5,  8, 11],
        [14, 17, 20, 23],
        [26, 29, 32, 35],
        [38, 41, 44, 47],
        [50, 53, 56, 59],
        [62, 65, 68, 71],
        [74, 77, 80, 83],
        [86, 89, 92, 69]])

In [271]:
tensor

tensor([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50, 53,
        56, 59, 62, 65, 68, 71, 74, 77, 80, 83, 86, 89, 92, 69])

In [272]:
ta = torch.tensor([1,2,3,4])
tb = torch.arange(4)
tb

tensor([0, 1, 2, 3])

In [273]:
ta + tb #addition

tensor([1, 3, 5, 7])

In [274]:
torch.add(ta,tb) # tensor longhand

tensor([1, 3, 5, 7])

In [275]:
torch.subtract(ta,tb) # alias => torch.sub(ta,tb) ,ta-tb

tensor([1, 1, 1, 1])

In [276]:
torch.mul(ta,tb) # alias => torch.multiply(ta,tb) ,ta*tb

tensor([ 0,  2,  6, 12])

In [277]:
torch.div(tb,ta) # alias => tb/ta

tensor([0.0000, 0.5000, 0.6667, 0.7500])

In [278]:
#remainder Modulus
tb % ta # alias => torch.remainder(tb,ta)

tensor([0, 1, 2, 3])

In [279]:
# Exponents
ta ** tb # torch.pow(ta,tb)

tensor([ 1,  2,  9, 64])

In [280]:
# another way to write longhand
ta.pow(tb)

tensor([ 1,  2,  9, 64])

In [281]:
# reassignment
ta += tb
ta

tensor([1, 3, 5, 7])

In [282]:
tb

tensor([0, 1, 2, 3])

In [283]:
tb.add_(ta)

tensor([ 1,  4,  7, 10])

In [284]:
tb

tensor([ 1,  4,  7, 10])

In [285]:
torch.cuda.is_available()

False

In [286]:
import pandas as pd

In [287]:
df = pd.read_csv('https://gist.githubusercontent.com/curran/a08a1080b88344b0c8a7/raw/0e7a9b0a5d22642a06d3d5b9bcbad9890c8ee534/iris.csv')
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [288]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [289]:
df['species'] = df['species'].astype('category')

In [290]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype   
---  ------        --------------  -----   
 0   sepal_length  150 non-null    float64 
 1   sepal_width   150 non-null    float64 
 2   petal_length  150 non-null    float64 
 3   petal_width   150 non-null    float64 
 4   species       150 non-null    category
dtypes: category(1), float64(4)
memory usage: 5.1 KB


In [291]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [292]:
df['species'] = df['species'].cat.codes

In [293]:
df.head()

sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [294]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    int8   
dtypes: float64(4), int8(1)
memory usage: 5.0 KB


In [295]:
X = df.drop(columns=['species'])
y = df['species']

In [296]:
from sklearn.model_selection import train_test_split

In [297]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4)


In [298]:
from sklearn.svm import SVC

In [299]:
model = SVC(kernel='linear')
model.fit(X_train, y_train)
model

SVC(kernel='linear')

In [300]:
from sklearn.metrics import f1_score,accuracy_score

accuracy_score(y_test, model.predict(X_test))

0.9833333333333333

In [301]:
# Assuming 'model' is a trained linear SVM model
weights = model.coef_
intercept = model.intercept_

print("Weights:", weights)
print("Intercept:", intercept)


Weights: [[-0.04627319  0.52114758 -1.00303682 -0.46412656]
 [ 0.04016065  0.16064259 -0.56224908 -0.24096389]
 [ 0.74831712  0.61403368 -2.04022523 -1.97660639]]
Intercept: [1.45299374 1.34136572 6.76608247]
